-- MySQL Script generated by MySQL Workbench
-- Tue Apr 27 20:32:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestorcursos
-- -----------------------------------------------------
--DROP DATABASE 'gestorcursos';
-- -----------------------------------------------------
-- Schema gestorcursos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestorcursos` DEFAULT CHARACTER SET utf8mb4 ;
USE `gestorcursos` ;

-- -----------------------------------------------------
-- Table `gestorcursos`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorcursos`.`registro` (
  `matricula` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorcursos`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorcursos`.`cursos` (
  `idcursos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `unidades` INT NULL,
  `examen` INT NULL,
  `tareas` INT NULL,
  `asistencias` INT NULL,
  `final` INT NULL,
  `registro_matricula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcursos`, `registro_matricula`),
  INDEX `fk_cursos_registro1_idx` (`registro_matricula` ASC),
  CONSTRAINT `fk_cursos_registro1`
    FOREIGN KEY (`registro_matricula`)
    REFERENCES `gestorcursos`.`registro` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorcursos`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorcursos`.`alumnos` (
  `idalumnos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `calExamenes` INT NULL,
  `calTareas` INT NULL,
  `calAsistencias` INT NULL,
  `calFinal` INT NULL,
  PRIMARY KEY (`idalumnos`),
  UNIQUE INDEX `idalumnos_UNIQUE` (`idalumnos` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorcursos`.`cursos_has_alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorcursos`.`cursos_has_alumnos` (
  `cursos_idcursos` INT NOT NULL,
  `cursos_registro_matricula` VARCHAR(45) NOT NULL,
  `alumnos_idalumnos` INT NOT NULL,
  PRIMARY KEY (`cursos_idcursos`, `cursos_registro_matricula`, `alumnos_idalumnos`),
  INDEX `fk_cursos_has_alumnos_alumnos1_idx` (`alumnos_idalumnos` ASC),
  INDEX `fk_cursos_has_alumnos_cursos1_idx` (`cursos_idcursos` ASC, `cursos_registro_matricula` ASC) ,
  CONSTRAINT `fk_cursos_has_alumnos_cursos1`
    FOREIGN KEY (`cursos_idcursos` , `cursos_registro_matricula`)
    REFERENCES `gestorcursos`.`cursos` (`idcursos` , `registro_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_alumnos_alumnos1`
    FOREIGN KEY (`alumnos_idalumnos`)
    REFERENCES `gestorcursos`.`alumnos` (`idalumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
