-- MySQL Script generated by MySQL Workbench
-- Thu Apr 29 13:09:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestorcursos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestorcursos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestorcursos` DEFAULT CHARACTER SET utf8mb4 ;
USE `gestorcursos` ;

-- -----------------------------------------------------
-- Table `gestorcursos`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorcursos`.`registro` (
  `matricula` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorcursos`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorcursos`.`cursos` (
  `idcursos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `unidades` INT NULL,
  `examen` INT NULL,
  `tareas` INT NULL,
  `asistencias` INT NULL,
  `registro_matricula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcursos`),
  UNIQUE INDEX `idcursos_UNIQUE` (`idcursos` ASC),
  CONSTRAINT `fk_cursos_registro1`
    FOREIGN KEY (`registro_matricula`)
    REFERENCES `gestorcursos`.`registro` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorcursos`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorcursos`.`alumnos` (
  `idalumnos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cursos_idcursos` INT NOT NULL,
  PRIMARY KEY (`idalumnos`),
  UNIQUE INDEX `idalumnos_UNIQUE` (`idalumnos` ASC),
  CONSTRAINT `fk_alumnos_cursos1`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `gestorcursos`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorcursos`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorcursos`.`unidades` (
  `idunidades` INT NOT NULL AUTO_INCREMENT,
  `examenes` INT NULL,
  `tareas` INT NULL,
  `asistencias` INT NULL,
  `cursos_idcursos` INT NOT NULL,
  PRIMARY KEY (`idunidades`),
  UNIQUE INDEX `idunidades_UNIQUE` (`idunidades` ASC),
  CONSTRAINT `fk_unidades_cursos1`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `gestorcursos`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorcursos`.`alumnosCalificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorcursos`.`alumnosCalificaciones` (
  `idalumnosCalificaciones` INT NOT NULL AUTO_INCREMENT,
  `calExamenes` INT NULL,
  `calTareas` INT NULL,
  `calAsistencias` INT NULL,
  `alumnos_idalumnos` INT NOT NULL,
  `unidades_idunidades` INT NOT NULL,
  PRIMARY KEY (`idalumnosCalificaciones`),
  CONSTRAINT `fk_alumnosCalificaciones_alumnos1`
    FOREIGN KEY (`alumnos_idalumnos`)
    REFERENCES `gestorcursos`.`alumnos` (`idalumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnosCalificaciones_unidades1`
    FOREIGN KEY (`unidades_idunidades`)
    REFERENCES `gestorcursos`.`unidades` (`idunidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
